---
title: "Data Story on Happy Moments"
author: "Wensong Qiao"
date: "2019Äê2ÔÂ6ÈÕ"
output: html_document
---
#Read data
```{r setup, include=FALSE}
setwd("C:/Users/qws/Desktop")
data<-read.csv("cleaned.csv")
```

#Install and load libraries
```{r, message=FALSE, warning=FALSE}
packages.used=c("tm", "wordcloud", "RColorBrewer", 
                "dplyr", "tydytext")
# check packages that need to be installed.
packages.needed=setdiff(packages.used, 
                        intersect(installed.packages()[,1], 
                                  packages.used))
# install additional packages
if(length(packages.needed)>0){
  install.packages(packages.needed, dependencies = TRUE,
                   repos='http://cran.us.r-project.org')
}
library(tm)
library(wordcloud)
library(RColorBrewer)
library(dplyr)
library(tidytext)
```

#Read in the speeches
```{r}
dataClean<-data[,5]
ff.all<-Corpus(VectorSource(dataClean))
```

#Text processing
```{r, warning=FALSE}
ff.all<-tm_map(ff.all, stripWhitespace)
ff.all<-tm_map(ff.all, content_transformer(tolower))
ff.all<-tm_map(ff.all, removeWords, stopwords("english"))
ff.all<-tm_map(ff.all, removeWords, character(0))
ff.all<-tm_map(ff.all, removePunctuation)
tdm.all<-DocumentTermMatrix(ff.all)
tdm.tidy=tidy(tdm.all)
tdm.overall=summarise(group_by(tdm.tidy, term), sum(count))

dtm <- DocumentTermMatrix(ff.all,
                          control = list(weighting = function(x)
                                             weightTfIdf(x, 
                                                         normalize =FALSE),
                                         stopwords = TRUE))
ff.dtm=tidy(dtm)
```

#Wordcloud
```{r, fig.height=6, fig.width=6,warning=False}
wordcloud(tdm.overall$term, tdm.overall$`sum(count)`,
          scale=c(7,0.1),
          max.words=500,
          min.freq=1,
          random.order=FALSE,
          rot.per=0.3,
          use.r.layout=T,
          random.color=FALSE,
          colors=brewer.pal(8,"Dark2"))
```

#Plot1``
```{r}
ggplot(Num, aes(x = data_cat, y = Freq, fill=factor(data_cat)))+
  geom_bar(stat = "identity")+
  ggtitle("The number of Happiness Predicted Topics")+
  xlab(NULL)+
  ylab(NULL)+
  theme(plot.title = element_text(hjust = 0.5),lengend.title=NULL)
```


#Plot2
```{r}
setwd("C:/Users/qws/Desktop/CU 2018 Fall/STAT 5243/WhatMakeUhappy/data/1/happydb/data/topic_dict")
enterainment<-as.data.frame(read.csv("entertainment-dict.csv",header = FALSE))
exercise<-as.data.frame(read.csv("exercise-dict.csv",header = FALSE))
family<-as.data.frame(read.csv("family-dict.csv",header = FALSE))
food<-as.data.frame(read.csv("food-dict.csv",header = FALSE))
people<-as.data.frame(read.csv("people-dict.csv",header = FALSE))
pets<-as.data.frame(read.csv("pets-dict.csv",header = FALSE))
school<-as.data.frame(read.csv("school-dict.csv",header = FALSE))
shopping<-as.data.frame(read.csv("shopping-dict.csv",header = FALSE))
work<-as.data.frame(read.csv("work-dict.csv",header = FALSE))

numtopic<-as.data.frame(c(nrow(exercise),nrow(family),nrow(food),nrow(people),nrow(pets),nrow(school),nrow(shopping),nrow(work)))

x=c("exercise","family","food","people","pets","school","shopping","work")
ggplot(numtopic)+
  geom_bar(aes(x=c("exercise","family","food","people","pets","school","shopping","work"),y=numtopic[,1],fill=factor(x)),stat="identity")+
  scale_fill_brewer(palette="Set2")+
  ggtitle("The types of Happiness things in each topic")+
  xlab(NULL)+
  ylab(NULL)+
  theme(plot.title = element_text(hjust = 0.5))+
  coord_flip()
```


